---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${vcap.services.mysql-service.credentials.jdbcUrl}
    username: ${vcap.services.mysql-service.credentials.username}
    password: ${vcap.services.mysql-service.credentials.password}
  jpa:
    hibernate.ddl-auto: none
    show_sql: false
